---
# Namespace level hard resource limits
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-quota
  namespace: secpoc
spec:
  hard:
    requests.cpu: "500m"
    requests.memory: 1Gi
    limits.cpu: "1000m"
    limits.memory: 2Gi

---
# Default resource limits at container level
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: secpoc
spec:
  limits:
  - default:
      memory: 500Mi
      cpu: "1000m"
    defaultRequest:
        memory: 100Mi
        cpu: "100m"
    type: Container
